import os
from dotenv import load_dotenv
load_dotenv()

from fastapi import FastAPI, Header, HTTPException
from pydantic import BaseModel
from src.graph import legal_assistant_pipeline

app = FastAPI(title="AI Lawyer Assistant API")

class ChatPayload(BaseModel):
    message: str
    chat_history: list = []
    turn_count: int = 0

@post("/api/v1/chat")
async def chat_endpoint(payload: ChatPayload, x_user_token: str = Header(None)):
    # Determine login state based on presence of a user token from backend session
    is_logged_in = x_user_token is not None and x_user_token != ""
    
    # Establish inputs mapped to our LangGraph state schema
    initial_state = {
        "messages": payload.chat_history + [{"role": "user", "content": payload.message}],
        "is_logged_in": is_logged_in,
        "turn_count": payload.turn_count,
        "max_free_turns": 3 # Hard boundary for anonymous users
    }
    
    try:
        # Run graph execution synchronously (or use .ainvoke for async)
        final_output = legal_assistant_pipeline.invoke(initial_state)
        
        # Grab the last structural response generated by the pipeline
        assistant_response = final_output["messages"][-1].content
        updated_turn_count = final_output["turn_count"]
        
        return {
            "response": assistant_response,
            "turn_count": updated_turn_count
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))